name: Build Spring Boot App

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: mvn -B clean verify -Pqa

      - name: Package release build
        run: mvn -B package -Prelease

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: springboot-artifacts
          path: target/*.jar